assignment2.sql

/***************************************
 * CSE 340 – Assignment 2
 * Database: test_340_g2s
 ***************************************/

-- =====================================
-- TASK 1: CRUD SQL STATEMENTS
-- =====================================

-- 1. INSERT Tony Stark
INSERT INTO public.account (
  account_firstname,
  account_lastname,
  account_email,
  account_password,
  account_type
) VALUES (
  'Tony',
  'Stark',
  'tony.stark@avengers.com',
  'iamironman',
  'Client'
);  

-- 2. UPDATE Tony Stark to Admin
UPDATE public.account
SET account_type = 'Admin'
WHERE account_email = 'tony.stark@avengers.com';

-- 3. DELETE Tony Stark
DELETE FROM public.account
WHERE account_email = 'tony.stark@avengers.com';

-- 4. UPDATE inventory description
UPDATE public.inventory
SET inv_description = REPLACE(
  inv_description,
  'the small interiors',
  'a huge interior'
)
WHERE inv_make = 'GM'
  AND inv_model = 'Hummer';

-- 5. SELECT with INNER JOIN
SELECT
  i.inv_make,
  i.inv_model,
  c.classification_name
FROM public.inventory i
INNER JOIN public.classification c
  ON i.classification_id = c.classification_id
WHERE c.classification_name = 'Sport';

-- 6. UPDATE image paths
UPDATE public.inventory
SET
  inv_image = REPLACE(inv_image, '/images/', '/images/vehicles/'),
  inv_thumbnail = REPLACE(inv_thumbnail, '/images/', '/images/vehicles/');

-- =====================================
-- TASK 2: BUILD DATABASE SCRIPT
-- =====================================

-- 7. CREATE classification table
CREATE TABLE IF NOT EXISTS public.classification (
  classification_id INT GENERATED BY DEFAULT AS IDENTITY,
  classification_name VARCHAR(30) NOT NULL,
  CONSTRAINT classification_pk PRIMARY KEY (classification_id)
);

-- 8. CREATE inventory table
CREATE TABLE IF NOT EXISTS public.inventory (
  inv_id INT GENERATED BY DEFAULT AS IDENTITY,
  inv_make VARCHAR(30) NOT NULL,
  inv_model VARCHAR(30) NOT NULL,
  inv_year CHAR(4) NOT NULL,
  inv_description TEXT NOT NULL,
  inv_image VARCHAR(100) NOT NULL,
  inv_thumbnail VARCHAR(100) NOT NULL,
  inv_price NUMERIC(10,2) NOT NULL,
  inv_miles INT NOT NULL,
  inv_color VARCHAR(20) NOT NULL,
  classification_id INT NOT NULL,
  CONSTRAINT inventory_pk PRIMARY KEY (inv_id),
  CONSTRAINT inventory_classification_fk
    FOREIGN KEY (classification_id)
    REFERENCES public.classification (classification_id)
);

-- 9. INSERT classifications
INSERT INTO public.classification (classification_name)
VALUES
  ('Sport'),
  ('SUV'),
  ('Truck'),
  ('Sedan');

-- 10. INSERT inventory data
INSERT INTO public.inventory (
  inv_make,
  inv_model,
  inv_year,
  inv_description,
  inv_image,
  inv_thumbnail,
  inv_price,
  inv_miles,
  inv_color,
  classification_id
)

VALUES (
  'GM',
  'Hummer',
  '2022',
  'This vehicle is known for the small interiors and powerful performance.',
  '/images/hummer.jpg',
  '/images/hummer-tn.jpg',
  85000.00,
  12000,
  'Black',
  1
);